-- Sample migration project v2: tasks referencing projects.
CREATE TABLE FBMCP_MIG_TASKS (
	ID INTEGER NOT NULL PRIMARY KEY,
	PROJECT_ID INTEGER NOT NULL REFERENCES FBMCP_MIG_PROJECTS (ID),
	TITLE VARCHAR(120) NOT NULL,
	DONE SMALLINT DEFAULT 0
);

CREATE INDEX FBMCP_MIG_TASKS_PROJECT ON FBMCP_MIG_TASKS (PROJECT_ID);

-- @down
DROP INDEX FBMCP_MIG_TASKS_PROJECT;

DROP TABLE FBMCP_MIG_TASKS;
