#!/usr/bin/env bash
# matrix-config.sh (D7 / E.5): generate fbmcp.dev.yaml for the container
# matrix and wait for every Firebird service to accept connections.
#
# The live tests reference the dev database ids (employee on fb5, spike3 on
# fb3); the generator maps those ids onto whichever container instance this
# run targets (FBMCP_MATRIX_INSTANCE, default fb50), so the same suite runs
# against every major. M4 executes and tunes this on the Docker host.
set -euo pipefail

cd "$(dirname "$0")/../.."   # repo root (fbmcp/)

INSTANCE="${FBMCP_MATRIX_INSTANCE:-fb50}"
HOST="${FBMCP_MATRIX_HOST:-fb50}"   # compose service name (runner network)
PORT="${FBMCP_MATRIX_PORT:-3050}"
PW="masterkey"

wait_for() { # host port label
  for _ in $(seq 1 60); do
    if (echo >/dev/tcp/"$1"/"$2") >/dev/null 2>&1; then
      echo "matrix: $3 ($1:$2) is accepting connections"
      return 0
    fi
    sleep 2
  done
  echo "matrix: $3 ($1:$2) never came up" >&2
  return 1
}

wait_for "$HOST" "$PORT" "$INSTANCE"

cat > fbmcp.dev.yaml <<EOF
# GENERATED by packaging/docker/matrix-config.sh — container matrix config.
# The ids (employee, spike3) match the live tests' expectations; both point
# at the one database the container bootstraps.
state:
    dir: /tmp/fbmcp-matrix-state
instances:
    - id: fb5
      addr: ${HOST}:${PORT}
      bin_dir: /usr/local/firebird/bin
      version: "5.0"
      service_user: SYSDBA
      service_secret_env: FBMCP_DEV_PW
      default_ro_user: SYSDBA
      default_ro_secret_env: FBMCP_DEV_PW
      default_admin_user: SYSDBA
      default_admin_secret_env: FBMCP_DEV_PW
      default_backup_dir: /tmp/fbmcp-matrix/backup
      default_work_dir: /tmp/fbmcp-matrix/work
    - id: fb3
      addr: ${HOST}:${PORT}
      bin_dir: /usr/local/firebird/bin
      version: "3.0"
      service_user: SYSDBA
      service_secret_env: FBMCP_DEV_PW
      default_ro_user: SYSDBA
      default_ro_secret_env: FBMCP_DEV_PW
      default_admin_user: SYSDBA
      default_admin_secret_env: FBMCP_DEV_PW
      default_backup_dir: /tmp/fbmcp-matrix/backup
      default_work_dir: /tmp/fbmcp-matrix/work
databases:
    - id: employee
      instance: fb5
      path: /firebird/data/employee.fdb
      ro_user: SYSDBA
      ro_secret_env: FBMCP_DEV_PW
      admin_user: SYSDBA
      admin_secret_env: FBMCP_DEV_PW
    - id: spike3
      instance: fb3
      path: /firebird/data/employee.fdb
      ro_user: SYSDBA
      ro_secret_env: FBMCP_DEV_PW
      admin_user: SYSDBA
      admin_secret_env: FBMCP_DEV_PW
trends: {}
EOF

mkdir -p /tmp/fbmcp-matrix/backup /tmp/fbmcp-matrix/work /tmp/fbmcp-matrix-state
echo "matrix: wrote fbmcp.dev.yaml (instance $INSTANCE at ${HOST}:${PORT})"
